/*
 * Generated by erpcgen 1.7.3 on Mon Mar 23 15:56:07 2020.
 *
 * AUTOGENERATED - DO NOT EDIT
 */


#if !defined(_bootloader_h_)
#define _bootloader_h_

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
// #include "erpc_version.h"

// #if 10703 != ERPC_VERSION_NUMBER
// #error "The generated shim code version is different to the rest of eRPC code."
// #endif

#if !defined(ERPC_TYPE_DEFINITIONS)
#define ERPC_TYPE_DEFINITIONS

// Enumerators data types declarations
typedef enum BootAction
{
    BOOT_NONE = 0,
    BOOT_APP_1 = 1,
    BOOT_APP_2 = 2,
    BOOT_BOOTLOADER = 255
} BootAction;

typedef enum AppId
{
    APP_1 = 0,
    APP_2 = 1,
    BOOTLOADER = 255
} AppId;

#endif // ERPC_TYPE_DEFINITIONS

/*! @brief Bootloader identifiers */
enum _Bootloader_ids
{
    kBootloader_service_id = 1,
    kBootloader_bl_ping_id = 1,
    kBootloader_bl_writePageBuffer_id = 2,
    kBootloader_bl_erasePageBuffer_id = 3,
    kBootloader_bl_eraseApp_id = 4,
    kBootloader_bl_writePage_id = 5,
    kBootloader_bl_setBootAction_id = 8,
    kBootloader_bl_boot_id = 9
};

#if defined(__cplusplus)
extern "C" {
#endif

//! @name Bootloader
//@{
void bl_ping(void);
int8_t bl_writePageBuffer(uint16_t offset, uint8_t data_len, const uint8_t * data);
void bl_erasePageBuffer(void);
int8_t bl_eraseApp(AppId app_id);
int8_t bl_writePage(AppId app_id, uint16_t page_no, uint32_t crc);
int8_t bl_setBootAction(BootAction action);
int8_t bl_boot();
//@} 

#if defined(__cplusplus)
}
#endif

#endif // _bootloader_h_
