#
# Generated by erpcgen 1.7.3 on Tue Mar 24 16:58:24 2020.
#
# AUTOGENERATED - DO NOT EDIT
#

import erpc

# Enumerators data types declarations
class BootAction:
    BOOT_NONE = 0
    BOOT_APP_1 = 1
    BOOT_APP_2 = 2
    BOOT_BOOTLOADER = 255

class AppId:
    APP_1 = 0
    APP_2 = 1
    BOOTLOADER = 255



