#
# Generated by erpcgen 1.7.3 on Tue Mar 24 16:58:24 2020.
#
# AUTOGENERATED - DO NOT EDIT
#

import erpc

# Abstract base class for Bootloader
class IBootloader(object):
    SERVICE_ID = 1
    BL_PING_ID = 1
    BL_WRITEPAGEBUFFER_ID = 2
    BL_ERASEPAGEBUFFER_ID = 3
    BL_ERASEAPP_ID = 4
    BL_WRITEPAGE_ID = 5
    BL_SETBOOTACTION_ID = 8
    BL_BOOT_ID = 9

    def bl_ping(self):
        raise NotImplementedError()

    def bl_writePageBuffer(self, offset, data):
        raise NotImplementedError()

    def bl_erasePageBuffer(self):
        raise NotImplementedError()

    def bl_eraseApp(self, app_id):
        raise NotImplementedError()

    def bl_writePage(self, page_no, crc):
        raise NotImplementedError()

    def bl_setBootAction(self, action):
        raise NotImplementedError()

    def bl_boot(self):
        raise NotImplementedError()


