#
# Generated by erpcgen 1.7.3 on Mon Mar 23 15:57:05 2020.
#
# AUTOGENERATED - DO NOT EDIT
#

import erpc
from . import common, interface

# Client for Bootloader
class BootloaderService(erpc.server.Service):
    def __init__(self, handler):
        super(BootloaderService, self).__init__(interface.IBootloader.SERVICE_ID)
        self._handler = handler
        self._methods = {
                interface.IBootloader.BL_PING_ID: self._handle_bl_ping,
            }

    def _handle_bl_ping(self, sequence, codec):
        # Read incoming parameters.

        # Invoke user implementation of remote function.
        self._handler.bl_ping()

        # Prepare codec for reply message.
        codec.reset()

        # Construct reply message.
        codec.start_write_message(erpc.codec.MessageInfo(
            type=erpc.codec.MessageType.kReplyMessage,
            service=interface.IBootloader.SERVICE_ID,
            request=interface.IBootloader.BL_PING_ID,
            sequence=sequence))


